name: CI

on:
  push:
    branches:
      - v1.x
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
      - v1.x
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.19, 1.21, 1.22]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod tidy

    - name: Install coverage tool
      run: go install github.com/mattn/goveralls@latest

    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out ./...

    - name: Upload coverage to Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
